name: brca_subtyping_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.2
  - r-deseq2
  - r-ggplot2
  - r-pheatmap
  - r-vsn
  - r-matrixstats
  - r-ggrepel
